project_id = "devdogs-website"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public","storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[api.tls]
enabled = false

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = false

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[storage.buckets.avatars]
public = true
file_size_limit = "5MiB"
# MIME types accepted by Next.js Image Optimization
allowed_mime_types = ["image/jpeg", "image/png", "image/gif", "image/webp", "image/avif"]

[auth]
enabled = true
site_url = "env(BASE_URL)"
additional_redirect_urls = ["env(BASE_URL)/api/auth/callback"]
enable_manual_linking = true

# [auth.hook.custom_access_token]
# enabled = true
# uri = "pg-functions://postgres/public/custom_access_token_hook"

[auth.oauth_server]
enabled = true

[auth.external.discord]
enabled = true
client_id = "env(DISCORD_CLIENT_ID)"
secret = "env(DISCORD_CLIENT_SECRET)"

[auth.external.github]
enabled = true
client_id = "env(GITHUB_CLIENT_ID)"
secret = "env(GITHUB_CLIENT_SECRET)"

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"
