query ClosedIssues($searchQuery: String!, $cursor: String) {
  search(query: $searchQuery, type: ISSUE, first: 100, after: $cursor) {
    pageInfo {
      hasNextPage
      endCursor
    }

    nodes {
      ... on Issue {
        closedAt

        assignees(first: 10) {
          nodes {
            databaseId
            login
            avatarUrl
          }
        }

        projectItems(first: 1) {
          nodes {
            quality: fieldValueByName(name: "Quality") {
              ... on ProjectV2ItemFieldSingleSelectValue {
                name
              }
            }

            priority: fieldValueByName(name: "Priority") {
              ... on ProjectV2ItemFieldSingleSelectValue {
                name
              }
            }

            complexity: fieldValueByName(name: "Complexity") {
              ... on ProjectV2ItemFieldSingleSelectValue {
                name
              }
            }
          }
        }
      }
    }
  }
}
